version: "3.9"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: bridge
    environment:
      PUID: ${PUID}          
      PGID: ${PGID}          
      TZ: ${TZ}              
      WEBUI_PORT: 8080
    volumes:
      - ./qbittorrent:/config
      - /mnt/hdd/downloads:/downloads
      - /mnt/hdd/completed:/completed
      - /mnt/hdd/watch:/watch
      - /mnt/hdd/media:/media
    ports:
      - "${QBITTORRENT_WEBUI_PORT}:8080"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: bridge
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./jellyfin:/config
      - /mnt/hdd/media:/media:ro
    ports:
      - "${JELLYFIN_WEBUI_PORT}:8096"      # веб-интерфейс Jellyfin (HTTP)
      # - "8920:8920"                      # (опц.) HTTPS, если настроишь сертификаты
    # devices:
    #   - /dev/dri:/dev/dri

# networks:
#   default:
#     driver: bridge
