services:
  qbittorrent:
    platform: linux/arm64/v8
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
      - ./qbittorrent:/config
      - /mnt/hdd/downloads:/downloads
      - /mnt/hdd/completed:/completed
      - /mnt/hdd/watch:/watch
      - /mnt/hdd/media:/media
    ports:
      - "${QBITTORRENT_WEBUI_PORT}:8080"

  jellyfin:
    platform: linux/arm64/v8
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./jellyfin:/config
      - /mnt/hdd/media:/media:ro
    ports:
      - "${JELLYFIN_WEBUI_PORT}:8096"
    # For HW accel later on Pi 4/5:
    # devices:
    #   - /dev/dri:/dev/dri
